services:
  site:
    build: ./frontendWeb
    depends_on:
      - server
    ports:
      - "80:80"
    volumes:
      - ./frontendWeb:/frontendWeb

  server:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend

  ai:
    build: ./ai
    depends_on:
      - server
    ports:
      - "5000:5000"
    volumes:
      - ./frontendWeb:/usr/share/nginx/html